### ISSUE TITLE
Doesn't return anything

### ISSUE THREAD

**Issue by cowboysdude** [Rayz224/rhasspy-IBMWatson#1]
I installed this exactly per instructions but when I ask a question it returns nothing.   

How and where do I check to see what's going?

Thank you for a great addition to Rhasspy and HA!

**Comment by Rayz224** [comment]
Hi,
have you tried to run the script by itself without Rhasspy? 

First navigate to the rhasspy/profiles/en directory : `cd .config/rhasspy/profiles/en/`
Then try to run the script : `sudo ./rhasspy_watson_says.sh "This is a test"`

It should output a whole lot of weird random characters, that's normal, it's the wav audio file sent on standard output.

Tell me how it goes and I'll able to help you more.

**Comment by cowboysdude** [comment]
I figured out what was wrong.  I installed it on the wrong computer.... I feel like an idiot.   So Sorry.
I installed with the docker container instructions but still getting nothing back....
